name: Install snmp

on:
  workflow_dispatch:
    inputs:
      site_to_check:
        description: "Test to check"
        required: false
        #default: 'onliner.by'
jobs:
  prepare:
    #runs-on: [my_runner]
    runs-on: ubuntu-20.04
    steps:
      - name: Install snmp
        run: sudo apt update && sudo apt install -y snmp snmp-mibs-downloader
      - run: echo "snmp has been installed"
      - run: |
          sudo sed -i '/^mibs /s/^/#/' /etc/snmp/snmp.conf
          snmptranslate 1.3.6.1.2.1.1 > snmp_translate.log 2>&1
          touch /tmp/file.log
          ls -la
      - name: Install Perl
        run: sudo apt-get install -y perl libxml-simple-perl libsnmp-perl
      - run: echo "Perl has been installed))"
      - name: Get The Script
        run: |
          curl https://raw.githubusercontent.com/cavaliercoder/mib2zabbix/master/mib2zabbix.pl > mib2zabbix
          chmod a+x mib2zabbix
          ./mib2zabbix -h >> snmp_translate.log 2>>&1
      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          path: snmp_+.log

