name: Check files and search tabs
on:
        push:
                pull_request:
jobs:
  Checkingfiles:
    runs-on: ubuntu-20.04
    steps:
    - name: Calculate the tabs
      run: |
        for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
          echo "$file was changed" >> report.log 
          echo "`cat $file |tr -cd '\t' | wc -c` Tabs in File." >> report.log
        done
    - name: Upload report
      uses: actions/upload-artifact@v3
      with:
        path: report.log

